### ISSUE TITLE
Reembolso 

### ISSUE THREAD

**Issue by Kikoalex** [gabrielfacci/walletsearch#1]
Reembolso do valor comprado não tem ajuda e não funciona aqui pra mim gostaria de ter meu valor comprado

**Comment by O1davisb** [comment]
Reembolso do valor  comprado n tem ajuda alguma

**Comment by Jeanluis27-web** [comment]
Gostaria de ter reembolso do minerador

**Comment by Kikoalex** [comment]
Meu valor reembolsado não tenho enteresse algum más quero meu dinheiro de volta em minha conta suporte orrivel.

**Comment by Jeanluis27-web** [comment]
Cancele a assinatura

Em sex., 21 de jun. de 2024, 14:07, Kikoalex ***@***.***>
escreveu:

**Comment by Kikoalex** [comment]
Ainda não teve meu valor reembolsado gostaria de como fazer para ter meu valor em conta

**Comment by Jeanluis27-web** [comment]
Bom dia ainda tenho meu valor estorno por favor me ajuda ai

**Comment by Jeanluis27-web** [comment]
Até hoje não recebi resposta do meu reembolso já mandei aqui no telegram

**Comment by Jeanluis27-web** [comment]
Me ajuda ai
